# Generated by Django 4.2.1 on 2023-10-29 20:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, help_text='CPF', max_length=500, null=True)),
                ('dt_nascimento', models.DateField(blank=True, help_text='Data de Nascimento', null=True)),
                ('endereco', models.CharField(blank=True, help_text='Endereço', max_length=500, null=True)),
                ('n_coletas', models.IntegerField(blank=True, help_text='Número de Coletas', null=True)),
                ('perfil', models.CharField(blank=True, help_text='Tipo de Produtor', max_length=150, null=True)),
                ('telefone', models.CharField(help_text='Telefone', max_length=500)),
                ('user_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('produtor', 'Produtor'), ('coletor', 'Coletor')], max_length=20), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
