# Generated by Django 4.2.1 on 2023-06-29 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(help_text='Tipo de Material', max_length=50)),
                ('estado', models.CharField(help_text='Condições do Produto', max_length=50)),
                ('peso', models.FloatField(help_text='Peso do produto', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor calculado pelo app', max_digits=10)),
                ('gps_coord', models.CharField(help_text='Coordenada gps da coleta', max_length=500)),
                ('produtor', models.ForeignKey(help_text='Nome do Ofertante', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='produtor.produtor')),
            ],
        ),
    ]
