# Generated by Django 4.2.1 on 2023-08-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_alter_oferta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
