# Generated by Django 4.2.1 on 2023-08-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0003_alter_oferta_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
    ]
